### ISSUE TITLE
New graphics patches

### ISSUE THREAD

**Issue by enumag** [07th-mod/higurashi-patch-compiler#17]
@ItaloKnox Here are the notes for you how to generate the new graphics patches. It will generate a patch with both PS3 and steam sprites. PS3 ones will have lipsync support.

It might be better to make the patch for just one chapter so that we can test everything. I don't want you to redo all patches if I made some error.

As always ask me if anything is unclear.

First you'll need to download some files:
- 1440p PS3 weather sprites from Iri
    - https://mega.nz/#!v80FAbxS!BQdOrCTbR98Yf1FTM-DXiZUEcAj0l0evSP5Ve3wRplg
- 1440p non weather sprites from our resources repo
    - https://github.com/07th-mod/resources/releases/download/Nipah/Higurashi-Portraits-1440p.7z
    - https://github.com/07th-mod/resources/releases/download/Nipah/Higurashi-Sprites-1440p.7z
- old graphics patches for the chapter you want to compile (only CGAlt directory is needed)
   - **Beware that tata has an additional sprite [here](https://github.com/07th-mod/tatarigoroshi/tree/master/CGAlt). I don't know if it is included in the old graphics patch or not.**
- shell scripts to generate the new patches
    - https://www.dropbox.com/s/qjmziqf4naigh5z/lipsync.zip?dl=0
    - Meakashi script is missing for now, we're working on it.

When you download and unzip everything, the directory structure should look like this:

```
<chapter>-old/ (for example onikakushi-old/)
    CGAlt/
sprites/ (Iri's 1440p weather sprites)
    Night/
        l/
        m/
    Sunset/
        l/
        m/
    Normal/
        l/ (images from Higurashi-Portraits-1440p.7z)
        m/ (images from Higurashi-Sprites-1440p.7z)
<chapter>.sh (for example onikakushi.sh)
```

Doublecheck that you have the structure correctly. It's easy to make it like `sprites/Normal/m/m/aka_Def_0.png` instead of `sprites/Normal/m/aka_Def_0.png`.

Now you just run the shell sript for the chapter you want. Each script will create new directory with the new patch. The patch should be compatible with the lip-sync branch which I'll push into each chapter repo today.

You'll see some errors like `cp: cannot stat 'himatsubushi-old/CGAlt/oryou_Def_0.png': No such file or directory` - ignore these, it's caused by characters not having steam sprites.

**Comment by ItaloKnox** [comment]
That looks very detailed and simple to run. I think I won't have much time to do this right now so is there a problem if we postpone this for a couple days? If you were actually looking forward to seeing it done in this time I can force through and build it, no problem at all. I'll probably find some time by night.

**Comment by enumag** [comment]
@ItaloKnox Take your time. Also P-Chang reported a little error in this so I need to fix that first.

**Comment by enumag** [comment]
I fixed the problem P-Chang reported. The shell scripts were changed a little so if you downlaoded them previously then get the new ones.

There is no problem if you postpone this for a few days.

**Comment by ItaloKnox** [comment]
I think we have quite a lot of missing files or wrong uppercase/lowercase names.

Onikakushi:
```
cp: cannot stat 'sprites/Normal/m/Kuma_Def_0.png': No such file or directory
cp: cannot stat 'sprites/Normal/m/Kuma_Def_1.png': No such file or directory
cp: cannot stat 'sprites/Normal/m/Kuma_Def_2.png': No such file or directory
cp: cannot stat 'onikakushi-old/CGAlt/Kuma_Def.png': No such file or directory
cp: cannot stat 'sprites/Normal/m/Kuma_Ikari_0.png': No such file or directory
cp: cannot stat 'sprites/Normal/m/Kuma_Ikari_1.png': No such file or directory
cp: cannot stat 'sprites/Normal/m/Kuma_Ikari_2.png': No such file or directory
cp: cannot stat 'onikakushi-old/CGAlt/Kuma_Ikari.png': No such file or directory
```

Watanagashi:
```
cp: cannot stat 'watanagashi-old/CGAlt/tomita1_Def.png': No such file or directory
cp: cannot stat 'watanagashi-old/CGAlt/oka1_Def.png': No such file or directory
cp: cannot stat 'watanagashi-old/CGAlt/tomita1_Odoroki.png': No such file or directory
cp: cannot stat 'watanagashi-old/CGAlt/oka1_Odoroki.png': No such file or directory
cp: cannot stat 'watanagashi-old/CGAlt/tomita1_Kanashimi.png': No such file or directory
cp: cannot stat 'watanagashi-old/CGAlt/tomita1_Tere.png': No such file or directory
cp: cannot stat 'watanagashi-old/CGAlt/oka1_Tere.png': No such file or directory
cp: cannot stat 'watanagashi-old/CGAlt/tomita1_Warai.png': No such file or directory
cp: cannot stat 'watanagashi-old/CGAlt/oka1_Warai.png': No such file or directory
cp: cannot stat 'sprites/Normal/l/re1b_waraiB1_0.png': No such file or directory
cp: cannot stat 'sprites/Normal/l/re1b_waraiB1_1.png': No such file or directory
cp: cannot stat 'sprites/Normal/l/re1b_waraiB1_2.png': No such file or directory
cp: cannot stat 'sprites/Normal/l/re1b_nandeB1_0.png': No such file or directory
cp: cannot stat 'sprites/Normal/l/re1b_nandeB1_1.png': No such file or directory
cp: cannot stat 'sprites/Normal/l/re1b_nandeB1_2.png': No such file or directory
cp: cannot stat 'sprites/Normal/m/Kuma_Def_0.png': No such file or directory
cp: cannot stat 'sprites/Normal/m/Kuma_Def_1.png': No such file or directory
cp: cannot stat 'sprites/Normal/m/Kuma_Def_2.png': No such file or directory
cp: cannot stat 'watanagashi-old/CGAlt/Kuma_Def.png': No such file or directory
cp: cannot stat 'watanagashi-old/CGAlt/ri_se_fu_a1_zoom.png': No such file or directory
cp: cannot stat 'sprites/Night/m/kasa_1_0.png': No such file or directory
cp: cannot stat 'sprites/Night/m/kasa_1_1.png': No such file or directory
cp: cannot stat 'sprites/Night/m/kasa_1_2.png': No such file or directory
cp: cannot stat 'sprites/Night/m/kasa_2_0.png': No such file or directory
cp: cannot stat 'sprites/Night/m/kasa_2_1.png': No such file or directory
cp: cannot stat 'sprites/Night/m/kasa_2_2.png': No such file or directory
```

Tatarigoroshi:
```
cp: cannot stat 'tatarigoroshi-old/CGAlt/oka1_Shinken.png': No such file or directory
cp: cannot stat 'tatarigoroshi-old/CGAlt/tomita1_Shinken.png': No such file or directory
cp: cannot stat 'tatarigoroshi-old/CGAlt/tomita1_Ikari_0.png': No such file or directory
cp: cannot stat 'tatarigoroshi-old/CGAlt/tomita1_Def.png': No such file or directory
cp: cannot stat 'tatarigoroshi-old/CGAlt/oka1_Def_0.png': No such file or directory
cp: cannot stat 'tatarigoroshi-old/CGAlt/tomita1_Odoroki.png': No such file or directory
cp: cannot stat 'tatarigoroshi-old/CGAlt/oka1_Odoroki_0.png': No such file or directory
cp: cannot stat 'tatarigoroshi-old/CGAlt/tomita1_Warai_0.png': No such file or directory
cp: cannot stat 'tatarigoroshi-old/CGAlt/oka1_Warai.png': No such file or directory
cp: cannot stat 'tatarigoroshi-old/CGAlt/tomita1_Kanashimi.png': No such file or directory
cp: cannot stat 'tatarigoroshi-old/CGAlt/kameda2a_Shinken_0.png': No such file or directory
cp: cannot stat 'tatarigoroshi-old/CGAlt/kameda2a_Warai_0.png': No such file or directory
cp: cannot stat 'tatarigoroshi-old/CGAlt/kameda2a_Def_0.png': No such file or directory
cp: cannot stat 'tatarigoroshi-old/CGAlt/kameda2a_Niyari_0.png': No such file or directory
cp: cannot stat 'tatarigoroshi-old/CGAlt/oka1_Tere_0.png': No such file or directory
cp: cannot stat 'tatarigoroshi-old/CGAlt/sa_se_hn_b2.png': No such file or directory
```

Himatsubushi:
```
cp: cannot stat 'himatsubushi-old/CGAlt/Sunset/ki_Warai_0.png': No such file or directory
cp: cannot stat 'himatsubushi-old/CGAlt/Sunset/ki_Def_0.png': No such file or directory
cp: cannot stat 'himatsubushi-old/CGAlt/oryou_Def_0.png': No such file or directory
cp: cannot stat 'himatsubushi-old/CGAlt/ki_Def_0.png': No such file or directory
cp: cannot stat 'himatsubushi-old/CGAlt/ki_Komaru_0.png': No such file or directory
cp: cannot stat 'himatsubushi-old/CGAlt/oryou_Warai_0.png': No such file or directory
cp: cannot stat 'himatsubushi-old/CGAlt/oryou_Shinken_0.png': No such file or directory
cp: cannot stat 'himatsubushi-old/CGAlt/miyuki_Hatena_0.png': No such file or directory
cp: cannot stat 'himatsubushi-old/CGAlt/miyuki_Kanashimi_0.png': No such file or directory
cp: cannot stat 'himatsubushi-old/CGAlt/miyuki_Huan_0.png': No such file or directory
cp: cannot stat 'himatsubushi-old/CGAlt/miyuki_Def_0.png': No such file or directory
cp: cannot stat 'himatsubushi-old/CGAlt/miyuki_Neboke_0.png': No such file or directory
cp: cannot stat 'himatsubushi-old/CGAlt/miyuki_Huan_0_zoom.png': No such file or directory
cp: cannot stat 'himatsubushi-old/CGAlt/miyuki_Hatena_0_zoom.png': No such file or directory
cp: cannot stat 'himatsubushi-old/CGAlt/miyuki_Def_0_zoom.png': No such file or directory
cp: cannot stat 'himatsubushi-old/CGAlt/miyuki_Warai_1_zoom.png': No such file or directory
cp: cannot stat 'himatsubushi-old/CGAlt/Sunset/oryou_Def_0.png': No such file or directory
cp: cannot stat 'himatsubushi-old/CGAlt/Sunset/oryou_Warai_0.png': No such file or directory
```

**Comment by ItaloKnox** [comment]
Oh boy, I think I'm getting blind or tired. Maybe both.

> You'll see some errors like cp: cannot stat 'himatsubushi-old/CGAlt/oryou_Def_0.png': No such file or directory - ignore these, it's caused by characters not having steam sprites.

So it's all false positives?

**Comment by ItaloKnox** [comment]
Just uploaded Onikakushi, both CG, and CGAlt. [I made a new tag for them](https://github.com/07th-mod/resources/releases/tag/Hanyuu), that one we're using is already cluttered enough.

We're still missing the backgrounds and CGs, but I think the total size shouldn't be that much bigger.

What should we do about those?

**Comment by enumag** [comment]
Tata and hima are all false positives. I'm not sure with oni and wata, I'll check...

P-Chang said he didn't want to rename BGs and CGs, just sprites.

**Comment by ItaloKnox** [comment]
Isn't it still an issue? Because we need to put the new versions (the problem wasn't just sprites) there and if I recall correctly they also have different names?

**Comment by enumag** [comment]
@ItaloKnox Damn. You're right of course, I forgot. Those might be difficult to fix. Create a new issue pls.

**Comment by enumag** [comment]
So some of oni and wata errors are actual bugs.

Onikakushi should be ok now, use [this updated script](https://www.dropbox.com/s/n5qzucaftki48ti/onikakushi.sh?dl=0).

Watanagashi is more problematic, we're actually missing some sprites in the 1440p packs. I'll need your help with this one @irlPM:

- Some portraits for Rena - `Normal/l/re1b_*`. But maybe we should use re1a_* instead in these cases?
- Night sprites for Kasa - `Night/m/kasa_*`. These should probably be added.

**Comment by P-Chang** [comment]
And uploaded new dll
http://www.mediafire.com/file/zoylo9o7oc81q81/chapter1dlls_v4.x.x.rar

there are no new feature, just cleaned up.

**Comment by irlPM** [comment]
Okay, I'll be cheking those remaning sprites. I'll take a look in the CGs/BG to see if I can rename them. Probably it will take about a week because of the holidays coming up.

**Comment by P-Chang** [comment]
`re1b` issue are probably related in naming miss of zoomed sprites in early edits of mod.

And I have some mistake of `Kuma`, I'll fix csv

**Comment by enumag** [comment]
@irlPM @P-Chang Any progress? I'd like to wrap this up (just the sprites, not talking about BGs here).

**Comment by enumag** [comment]
@irlPM Can you check the missing portraits for Rena and missing night sprites for Kasai? It's blocking my progress with new graphics patch compiler.
